// AUTO-GENERATED by scripts/build-images.py — do not edit by hand.

export type ImageVariant = { file: string; width: number; height: number; bytes: number };
export type ImageEntry = { variants: ImageVariant[]; source?: string };

export type ImageKey =
  | "aerialMarket"
  | "apartmentBalconies"
  | "apartmentFacade"
  | "apartmentLowAngle"
  | "blueprintReview"
  | "building1"
  | "building2"
  | "building4"
  | "building5"
  | "concreteBuilding"
  | "engineersSite"
  | "excavatorSand"
  | "excavatorSite"
  | "generalSecretary"
  | "helmetCloseup"
  | "heroCrane"
  | "highRise"
  | "highRiseCloud"
  | "homepageBuilding"
  | "interiorPainting"
  | "interiorRoom"
  | "loader"
  | "logo"
  | "managingDirector"
  | "projectManager"
  | "roadHeavyMachinery"
  | "roadMachinery"
  | "roadRoller"
  | "roadWorkCrew"
  | "shipyardWorkers"
  | "siteCranes"
  | "teamDiscussion"
  | "workersDiscuss"
  | "workersSmiling"
;

export const IMAGE_MANIFEST: Record<ImageKey, ImageEntry> = {
  "aerialMarket": {"variants": [{"file": "aerial-market-640.webp", "width": 640, "height": 427, "bytes": 59176}, {"file": "aerial-market-1280.webp", "width": 1280, "height": 854, "bytes": 165748}], "source": "https://images.pexels.com/photos/31619956/pexels-photo-31619956.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "apartmentBalconies": {"variants": [{"file": "apartment-balconies-640.webp", "width": 640, "height": 427, "bytes": 35026}, {"file": "apartment-balconies-1280.webp", "width": 1280, "height": 854, "bytes": 88134}], "source": "https://images.pexels.com/photos/29174529/pexels-photo-29174529.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "apartmentFacade": {"variants": [{"file": "apartment-facade-640.webp", "width": 640, "height": 427, "bytes": 24540}, {"file": "apartment-facade-1280.webp", "width": 1280, "height": 854, "bytes": 55268}], "source": "https://images.pexels.com/photos/27459248/pexels-photo-27459248.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "apartmentLowAngle": {"variants": [{"file": "apartment-low-angle-640.webp", "width": 640, "height": 427, "bytes": 27974}, {"file": "apartment-low-angle-1280.webp", "width": 1280, "height": 854, "bytes": 68314}], "source": "https://images.pexels.com/photos/25033113/pexels-photo-25033113.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "blueprintReview": {"variants": [{"file": "blueprint-review-640.webp", "width": 640, "height": 427, "bytes": 37054}, {"file": "blueprint-review-1280.webp", "width": 1280, "height": 854, "bytes": 73428}], "source": "https://images.pexels.com/photos/8961133/pexels-photo-8961133.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "building1": {"variants": [{"file": "building1-480.webp", "width": 480, "height": 320, "bytes": 39698}, {"file": "building1-640.webp", "width": 640, "height": 426, "bytes": 67134}, {"file": "building1-960.webp", "width": 960, "height": 639, "bytes": 126870}]},
  "building2": {"variants": [{"file": "building2-480.webp", "width": 480, "height": 640, "bytes": 55262}, {"file": "building2-640.webp", "width": 640, "height": 853, "bytes": 90628}, {"file": "building2-960.webp", "width": 960, "height": 1280, "bytes": 154804}]},
  "building4": {"variants": [{"file": "building4-640.webp", "width": 640, "height": 480, "bytes": 104546}, {"file": "building4-1280.webp", "width": 1280, "height": 960, "bytes": 329828}, {"file": "building4-1920.webp", "width": 1920, "height": 1440, "bytes": 602902}]},
  "building5": {"variants": [{"file": "building5-640.webp", "width": 640, "height": 480, "bytes": 104786}, {"file": "building5-1280.webp", "width": 1280, "height": 960, "bytes": 331650}]},
  "concreteBuilding": {"variants": [{"file": "concrete-building-640.webp", "width": 640, "height": 427, "bytes": 45222}, {"file": "concrete-building-1280.webp", "width": 1280, "height": 854, "bytes": 127182}], "source": "https://images.pexels.com/photos/1463917/pexels-photo-1463917.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "engineersSite": {"variants": [{"file": "engineers-site-640.webp", "width": 640, "height": 427, "bytes": 42602}, {"file": "engineers-site-1280.webp", "width": 1280, "height": 854, "bytes": 86682}], "source": "https://images.pexels.com/photos/8961065/pexels-photo-8961065.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "excavatorSand": {"variants": [{"file": "excavator-sand-640.webp", "width": 640, "height": 427, "bytes": 78048}, {"file": "excavator-sand-1280.webp", "width": 1280, "height": 854, "bytes": 222392}], "source": "https://images.pexels.com/photos/33870733/pexels-photo-33870733.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "excavatorSite": {"variants": [{"file": "excavator-site-640.webp", "width": 640, "height": 427, "bytes": 63204}, {"file": "excavator-site-1280.webp", "width": 1280, "height": 854, "bytes": 180320}], "source": "https://images.pexels.com/photos/20296265/pexels-photo-20296265.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "generalSecretary": {"variants": [{"file": "general-secretary-480.webp", "width": 480, "height": 651, "bytes": 35440}, {"file": "general-secretary-840.webp", "width": 840, "height": 1140, "bytes": 77536}]},
  "helmetCloseup": {"variants": [{"file": "helmet-closeup-640.webp", "width": 640, "height": 427, "bytes": 19302}, {"file": "helmet-closeup-1280.webp", "width": 1280, "height": 854, "bytes": 42618}], "source": "https://images.pexels.com/photos/34965713/pexels-photo-34965713.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "heroCrane": {"variants": [{"file": "hero-crane-640.webp", "width": 640, "height": 360, "bytes": 30708}, {"file": "hero-crane-1280.webp", "width": 1280, "height": 720, "bytes": 72990}, {"file": "hero-crane-1600.webp", "width": 1600, "height": 900, "bytes": 99838}], "source": "https://images.pexels.com/photos/15183903/pexels-photo-15183903.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=900"},
  "highRise": {"variants": [{"file": "high-rise-640.webp", "width": 640, "height": 427, "bytes": 25322}, {"file": "high-rise-1280.webp", "width": 1280, "height": 854, "bytes": 65588}], "source": "https://images.pexels.com/photos/37431888/pexels-photo-37431888.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "highRiseCloud": {"variants": [{"file": "high-rise-cloud-640.webp", "width": 640, "height": 427, "bytes": 10076}, {"file": "high-rise-cloud-1280.webp", "width": 1280, "height": 854, "bytes": 27014}], "source": "https://images.pexels.com/photos/9370034/pexels-photo-9370034.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "homepageBuilding": {"variants": [{"file": "homepage-building-480.webp", "width": 480, "height": 640, "bytes": 50244}, {"file": "homepage-building-640.webp", "width": 640, "height": 853, "bytes": 88056}, {"file": "homepage-building-960.webp", "width": 960, "height": 1280, "bytes": 177588}]},
  "interiorPainting": {"variants": [{"file": "interior-painting-640.webp", "width": 640, "height": 427, "bytes": 8250}, {"file": "interior-painting-1280.webp", "width": 1280, "height": 854, "bytes": 19586}], "source": "https://images.pexels.com/photos/6473966/pexels-photo-6473966.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "interiorRoom": {"variants": [{"file": "interior-room-640.webp", "width": 640, "height": 427, "bytes": 13220}, {"file": "interior-room-1280.webp", "width": 1280, "height": 854, "bytes": 32192}], "source": "https://images.pexels.com/photos/7028110/pexels-photo-7028110.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "loader": {"variants": [{"file": "loader-640.webp", "width": 640, "height": 427, "bytes": 64166}, {"file": "loader-1280.webp", "width": 1280, "height": 854, "bytes": 197934}], "source": "https://images.pexels.com/photos/416988/pexels-photo-416988.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "logo": {"variants": [{"file": "logo-320.webp", "width": 320, "height": 320, "bytes": 15104}]},
  "managingDirector": {"variants": [{"file": "managing-director-480.webp", "width": 480, "height": 510, "bytes": 13952}, {"file": "managing-director-960.webp", "width": 960, "height": 1020, "bytes": 37982}]},
  "projectManager": {"variants": [{"file": "project-manager-480.webp", "width": 480, "height": 640, "bytes": 14260}, {"file": "project-manager-960.webp", "width": 960, "height": 1280, "bytes": 35982}]},
  "roadHeavyMachinery": {"variants": [{"file": "road-heavy-machinery-640.webp", "width": 640, "height": 427, "bytes": 40270}, {"file": "road-heavy-machinery-1280.webp", "width": 1280, "height": 854, "bytes": 158730}], "source": "https://images.pexels.com/photos/17605960/pexels-photo-17605960.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "roadMachinery": {"variants": [{"file": "road-machinery-640.webp", "width": 640, "height": 427, "bytes": 74796}, {"file": "road-machinery-1280.webp", "width": 1280, "height": 854, "bytes": 279726}], "source": "https://images.pexels.com/photos/34338597/pexels-photo-34338597.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "roadRoller": {"variants": [{"file": "road-roller-640.webp", "width": 640, "height": 427, "bytes": 61870}, {"file": "road-roller-1280.webp", "width": 1280, "height": 854, "bytes": 153882}], "source": "https://images.pexels.com/photos/12274274/pexels-photo-12274274.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "roadWorkCrew": {"variants": [{"file": "road-work-crew-640.webp", "width": 640, "height": 427, "bytes": 45330}, {"file": "road-work-crew-1280.webp", "width": 1280, "height": 854, "bytes": 165848}], "source": "https://images.pexels.com/photos/34053335/pexels-photo-34053335.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "shipyardWorkers": {"variants": [{"file": "shipyard-workers-640.webp", "width": 640, "height": 427, "bytes": 33716}, {"file": "shipyard-workers-1280.webp", "width": 1280, "height": 854, "bytes": 87220}], "source": "https://images.pexels.com/photos/37663550/pexels-photo-37663550.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "siteCranes": {"variants": [{"file": "site-cranes-640.webp", "width": 640, "height": 427, "bytes": 37318}, {"file": "site-cranes-1280.webp", "width": 1280, "height": 854, "bytes": 108712}], "source": "https://images.pexels.com/photos/5505119/pexels-photo-5505119.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "teamDiscussion": {"variants": [{"file": "team-discussion-640.webp", "width": 640, "height": 427, "bytes": 15206}, {"file": "team-discussion-1280.webp", "width": 1280, "height": 854, "bytes": 32602}], "source": "https://images.pexels.com/photos/6566819/pexels-photo-6566819.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "workersDiscuss": {"variants": [{"file": "workers-discuss-640.webp", "width": 640, "height": 427, "bytes": 24424}, {"file": "workers-discuss-1280.webp", "width": 1280, "height": 854, "bytes": 51058}], "source": "https://images.pexels.com/photos/8961034/pexels-photo-8961034.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
  "workersSmiling": {"variants": [{"file": "workers-smiling-640.webp", "width": 640, "height": 427, "bytes": 27058}, {"file": "workers-smiling-1280.webp", "width": 1280, "height": 854, "bytes": 55562}], "source": "https://images.pexels.com/photos/8961068/pexels-photo-8961068.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=1600&h=1067"},
};
